name: Package

permissions:
  contents: read

on:
  workflow_call:

jobs:
  main:
    env:
      OUTBASEDIR: .output
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          # Need full history for version calculation in in ./utils/gitinfo.ts
          fetch-depth: 0
      - name: Set up pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 'latest'
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'
      - name: Install dependencies
        shell: bash
        run: pnpm install
      - name: Package plugin
        run: pnpm run package
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ vars.PLUGIN_NAME }}.xpi
          path: ${{ env.OUTBASEDIR }}/${{ vars.PLUGIN_NAME }}-*.xpi
          archive: false
      - name: Upload update.json artifact
        uses: actions/upload-artifact@v7
        with:
          name: update.json
          path: ${{ env.OUTBASEDIR }}/update.json
          archive: false
