name: Package

permissions:
  contents: read

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          # Need full history for version calculation in in ./utils/gitinfo.ts
          fetch-depth: 0
      - name: Set up pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 'latest'
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'
      - name: Install dependencies
        shell: bash
        run: pnpm install
      - name: Package plugin
        run: pnpm run package
      - name: Get plugin file path
        id: get_plugin_path
        run: echo "PLUGIN_FILE=$(find ${{ vars.OUTBASEDIR }} -name '*.xpi' | head -n 1)" >> "$GITHUB_OUTPUT"
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.get_plugin_path.outputs.PLUGIN_FILE }}
          archive: false
      - name: Upload update.json artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ vars.OUTBASEDIR }}/update.json
          archive: false
